### PR TITLE
feat: add nest add support

### LINKED ISSUE #30: Feature: add ng add support
Add ng-add support to library:

`ng add` will
* add module to imports on `app.module.ts`
* add package to package.json

### PR DESCRIPTION
**Pull request by santoshyadavdev**
Fixes #30

### CODE REVIEW

**Comment by wesleygrimes** [comment]
Thanks @santoshyadav198613! This is excited. Looks like you need to do a rebase on master to resolve some conflicts.

Also, is the prettier hook running on your side? Seeing some oddities in the formatting of code.

**Comment by santoshyadavdev** [comment]
Ohh I will verify again tomorrow, why it didn't worked during commit, i am working on adding to import part will close this by weekend.

**Comment by santoshyadavdev** [comment]
Hi @wesleygrimes ,

I am not able to commit the changes attached is the log it always fails at pre commit hook, I am using windows.
[2019-08-29T19_35_49_971Z-debug.log](https://github.com/nestjs-addons/in-memory-db/files/3557075/2019-08-29T19_35_49_971Z-debug.log)

**Comment by wesleygrimes** [comment]
@all-contributors please add @santoshyadav198613 for code, tests

**Pull request closed without merging**
