### PR TITLE
feat: implement configuration via forRoot

### PR DESCRIPTION
**Pull request by wescopeland**
Adds the ability to provide configuration to the InMemoryDBModule. 

- Add a static method `forRoot` to `InMemoryDBModule`

impl #18

### CODE REVIEW

**Comment by wesleygrimes** [comment]
Is there a way to get around requiring forFeature? I want to keep this simple for folks that don’t want to take advantage of configuring it.

**Comment by wescopeland** [comment]
I felt the same way -- wasn't able to quickly figure it out. Let me play around with it some more.

**Comment by cmwhited** [comment]
I actually think that adding `forFeature` is a solid route to go. It allows you to define a model for a feature and enforces `package-by-feature`, also, it follows the established pattern that nestjs has established.

**Comment by wesleygrimes** [comment]
Thanks y’all for taking this on! I like the concept of forFeature as well. But there is that base set of people that will be like “I just want to throw together a quick one service prototype” and for them I’d like to keep it simple. 

But definitely agree, providing the ability to have forFeature will solve the issue of injecting this thing into multiple controllers, each with their own dbs. Very powerful.

**Comment by wescopeland** [comment]
Understood. I have this figured out on how to make `forFeature` optional, I'll push the change.

**Comment by wesleygrimes** [comment]
@wescopeland so with using `forFeature` how will we know which instance of the service the feature applies to? At present, there isn't a way to inject multiple instances of `InMemoryDBService`?

I'm just thinking out loud here, but maybe for this first implementation of Configuration we go with `forRoot` since there is really no concept of feature-based instances yet.

**Review by wesleygrimes — APPROVED** [review]

**Pull request merged**
