### PR TITLE
[WIP] refactor: use Map

### PR DESCRIPTION
**Pull request by wesleygrimes**
work in progress, this is *very* broken at present, trying to eliminate breaking changes as well

### CODE REVIEW

**Comment by jordanpowell88** [comment]
This feels like a much cleaner solution and gives us more flexibility moving forward. The ability to pass in a generic Key type is pretty useful feature.

**Comment by wesleygrimes** [comment]
Any thoughts on moving forward? Should we create this as a new service/module? Or maybe we create schematics to migrate folks?

Either way I think it needs to happen as a version 2 breaking change.

**Comment by jordanpowell88** [comment]
My thoughts would be to keep it in the same module and add as a version 2 feature. Providing a schematic could make easy transition for those upgrading

**Comment by wesleygrimes** [comment]
Agreed. I’m hoping to get some more time this week to hack on it.

**Comment by cmwhited** [comment]
Creating a schematic that you can run to migrate sounds like the right path. I like the changes. I think it is much more resilient and easier to maintain.

**Comment by wesleygrimes** [comment]
Moving over to the mono-repo. Can reopen there. https://github.com/nestjs-addons/platform

**Pull request closed without merging**
